In [1]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.config import EXPERIMENT_LOG_FILE

log_df = pd.read_csv(EXPERIMENT_LOG_FILE)

metric_cols = ["test_MAE", "test_RMSE", "test_MAPE", "test_sMAPE", "test_R2"]
for col in metric_cols:
    log_df[col] = pd.to_numeric(log_df[col], errors="coerce")

log_df.head()

,run_id,timestamp,target,dataset_name,frequency,detected_frequency,feature_set_name,data_mode,model_name,model_params,...,test_MAE,test_RMSE,test_MAPE,test_sMAPE,test_R2,model_path,prediction_path,diagnostic_plot_path,feature_importance_path,params_path
0,run_20260326_135954_1beb8be6,2026-03-26 13:59:54,BA_TotActPwr_BESS_AC_Panel1,Imputed_data,5min,5min,all_features_v1,dense,linear_regression,"{""copy_X"": true, ""fit_intercept"": true, ""n_job...",...,0.227493,0.593984,24.804799,15.843181,0.927327,C:\Data_analysis\Thesis\outputs\models\run_202...,C:\Data_analysis\Thesis\outputs\predictions\ru...,C:\Data_analysis\Thesis\outputs\figures\foreca...,C:\Data_analysis\Thesis\outputs\feature_import...,C:\Data_analysis\Thesis\outputs\logs\run_20260...
1,run_20260326_135955_2ded4f36,2026-03-26 13:59:55,BA_TotActPwr_BESS_AC_Panel1,Imputed_data,5min,5min,all_features_v1,dense,ridge,"{""alpha"": 1.0, ""copy_X"": true, ""fit_intercept""...",...,0.227476,0.593980,24.802236,15.840235,0.927328,C:\Data_analysis\Thesis\outputs\models\run_202...,C:\Data_analysis\Thesis\outputs\predictions\ru...,C:\Data_analysis\Thesis\outputs\figures\foreca...,C:\Data_analysis\Thesis\outputs\feature_import...,C:\Data_analysis\Thesis\outputs\logs\run_20260...
2,run_20260326_135956_f45e2aad,2026-03-26 13:59:56,BA_TotActPwr_BESS_AC_Panel1,Imputed_data,5min,5min,all_features_v1,dense,random_forest,"{""bootstrap"": true, ""ccp_alpha"": 0.0, ""criteri...",...,0.274168,0.675291,29.245611,16.788629,0.906070,C:\Data_analysis\Thesis\outputs\models\run_202...,C:\Data_analysis\Thesis\outputs\predictions\ru...,C:\Data_analysis\Thesis\outputs\figures\foreca...,C:\Data_analysis\Thesis\outputs\feature_import...,C:\Data_analysis\Thesis\outputs\logs\run_20260...
3,run_20260326_140213_03187aa3,2026-03-26 14:02:13,BA_TotActPwr_BESS_AC_Panel1,Imputed_data,5min,5min,all_features_v1,dense,xgboost,"{""objective"": ""reg:squarederror"", ""base_score""...",...,0.243553,0.727950,20.211308,11.535189,0.890849,C:\Data_analysis\Thesis\outputs\models\run_202...,C:\Data_analysis\Thesis\outputs\predictions\ru...,C:\Data_analysis\Thesis\outputs\figures\foreca...,C:\Data_analysis\Thesis\outputs\feature_import...,C:\Data_analysis\Thesis\outputs\logs\run_20260...
4,run_20260326_140231_10cb28a9,2026-03-26 14:02:31,BA_TotActPwr_BESS_AC_Panel1,Data_with_NaNs,5min,5min,all_features_v1,nan_friendly,hist_gbr,"{""categorical_features"": ""from_dtype"", ""early_...",...,0.226474,0.695078,21.175391,12.846201,0.900681,C:\Data_analysis\Thesis\outputs\models\run_202...,C:\Data_analysis\Thesis\outputs\predictions\ru...,C:\Data_analysis\Thesis\outputs\figures\foreca...,NaN,C:\Data_analysis\Thesis\outputs\logs\run_20260...

In [2]:
academy_results = log_df[
    (log_df["target"] == "BU_TotActPwr_Tech_Room") &
    (log_df["feature_set_name"] == "all_features_v1")
].copy()  #    (log_df["target"] == "BU_TotActPwr_Tech_Room") &

academy_results = academy_results.sort_values("test_RMSE", ascending=True)

academy_results[
    [
        "run_id",
        "model_name",
        "target",
        "dataset_name",
        "data_mode",
        "frequency",
        "feature_set_name",
        "test_MAE",
        "test_RMSE",
        "test_MAPE",
        "test_sMAPE",
        "test_R2",
    ]
]

,run_id,model_name,target,dataset_name,data_mode,frequency,feature_set_name,test_MAE,test_RMSE,test_MAPE,test_sMAPE,test_R2
47,run_20260326_154931_8ed0b63f,xgboost,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,15min,all_features_v1,0.085095,0.162799,5.577106,5.274815,0.987085
46,run_20260326_154926_46b36d2e,hist_gbr,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,15min,all_features_v1,0.087242,0.169788,5.666668,5.340051,0.985953
45,run_20260326_154922_31a527a4,xgboost,BU_TotActPwr_Tech_Room,Imputed_data,dense,15min,all_features_v1,0.090972,0.172347,6.118888,5.658857,0.985611
44,run_20260326_154859_42489288,random_forest,BU_TotActPwr_Tech_Room,Imputed_data,dense,15min,all_features_v1,0.091427,0.180622,5.675108,5.322888,0.984196
48,run_20260326_154936_5b452af6,catboost,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,15min,all_features_v1,0.098916,0.181105,6.133532,5.839951,0.984018
52,run_20260326_155207_f9a2d458,xgboost,BU_TotActPwr_Tech_Room,Imputed_data,dense,5min,all_features_v1,0.094804,0.192072,6.081118,5.539115,0.982288
54,run_20260326_155218_608181c3,xgboost,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,5min,all_features_v1,0.097528,0.192141,6.035875,5.552447,0.982253
53,run_20260326_155212_e3f6694c,hist_gbr,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,5min,all_features_v1,0.099742,0.197695,6.032272,5.602039,0.981212
51,run_20260326_155037_96cfe428,random_forest,BU_TotActPwr_Tech_Room,Imputed_data,dense,5min,all_features_v1,0.094316,0.198051,6.105730,5.558563,0.981169
55,run_20260326_155226_e0c9bc90,catboost,BU_TotActPwr_Tech_Room,Data_with_NaNs,nan_friendly,5min,all_features_v1,0.104481,0.203975,6.478658,5.962691,0.979999
49,run_20260326_155035_da2c1372,linear_regression,BU_TotActPwr_Tech_Room,Imputed_data,dense,5min,all_features_v1,0.118009,0.231712,7.718715,7.027587,0.974223
50,run_20260326_155036_abef64dc,ridge,BU_TotActPwr_Tech_Room,Imputed_data,dense,5min,all_features_v1,0.118010,0.231714,7.718866,7.027577,0.974223
43,run_20260326_154858_98ecd460,ridge,BU_TotActPwr_Tech_Room,Imputed_data,dense,15min,all_features_v1,0.140397,0.242415,9.139957,8.514547,0.971533
42,run_20260326_154857_f3d804f1,linear_regression,BU_TotActPwr_Tech_Room,Imputed_data,dense,15min,all_features_v1,0.140518,0.242420,9.148846,8.523091,0.971532

In [3]:
academy_compare = log_df[
    (log_df["feature_set_name"] == "all_features_v1")
].copy()   #(log_df["target"] == "BU_TotActPwr_Academy") &

academy_compare["test_RMSE"] = pd.to_numeric(academy_compare["test_RMSE"], errors="coerce")
academy_compare = academy_compare.dropna(subset=["test_RMSE"])

best_per_dataset = (
    academy_compare.sort_values("test_RMSE", ascending=True)
    .groupby("dataset_name", as_index=False)
    .first()
)

best_per_dataset[
    [
        "dataset_name",
        "model_name",
        "target",
        "data_mode",
        "test_MAE",
        "test_RMSE",
        "test_MAPE",
        "test_sMAPE",
        "test_R2",
    ]
]

,dataset_name,model_name,target,data_mode,test_MAE,test_RMSE,test_MAPE,test_sMAPE,test_R2
0,Data_with_NaNs,xgboost,BU_TotActPwr_Tech_Room,nan_friendly,0.085095,0.162799,5.577106,5.274815,0.987085
1,Imputed_data,xgboost,BU_TotActPwr_Tech_Room,dense,0.090972,0.172347,6.118888,5.658857,0.985611

In [4]:
academy_compare = log_df[

    (log_df["feature_set_name"] == "all_features_v1")
].copy()
#  (log_df["target"] == "BU_TotActPwr_Academy") &
academy_compare = academy_compare.sort_values(
    ["dataset_name", "test_RMSE"], ascending=[True, True]
)

academy_compare[
    [
        "run_id",
        "model_name",
        "dataset_name",
        "target",
        "data_mode",
        "test_MAE",
        "test_RMSE",
        "test_MAPE",
        "test_sMAPE",
        "test_R2",
    ]
]

,run_id,model_name,dataset_name,target,data_mode,test_MAE,test_RMSE,test_MAPE,test_sMAPE,test_R2
47,run_20260326_154931_8ed0b63f,xgboost,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.085095,0.162799,5.577106,5.274815,0.987085
46,run_20260326_154926_46b36d2e,hist_gbr,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.087242,0.169788,5.666668,5.340051,0.985953
48,run_20260326_154936_5b452af6,catboost,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.098916,0.181105,6.133532,5.839951,0.984018
54,run_20260326_155218_608181c3,xgboost,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.097528,0.192141,6.035875,5.552447,0.982253
53,run_20260326_155212_e3f6694c,hist_gbr,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.099742,0.197695,6.032272,5.602039,0.981212
55,run_20260326_155226_e0c9bc90,catboost,Data_with_NaNs,BU_TotActPwr_Tech_Room,nan_friendly,0.104481,0.203975,6.478658,5.962691,0.979999
58,run_20260327_085035_b375ea4c,catboost,Data_with_NaNs,BU_TotActPwr_SDB_EL_Substation,nan_friendly,0.345614,0.488030,5.291563,5.287460,0.867431
56,run_20260327_085019_0009dc76,hist_gbr,Data_with_NaNs,BU_TotActPwr_SDB_EL_Substation,nan_friendly,0.367030,0.509970,5.811188,5.776749,0.855243
57,run_20260327_085028_3d3b1bad,xgboost,Data_with_NaNs,BU_TotActPwr_SDB_EL_Substation,nan_friendly,0.444999,0.575930,6.734293,6.800945,0.815375
4,run_20260326_140231_10cb28a9,hist_gbr,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.226474,0.695078,21.175391,12.846201,0.900681
25,run_20260326_153757_22c49794,hist_gbr,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.244418,0.704219,18.027195,13.296460,0.929780
6,run_20260326_140310_a1a3b939,catboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.238647,0.708564,23.115788,12.849856,0.896789
5,run_20260326_140254_5bc6e269,xgboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.244880,0.727345,20.693209,11.561437,0.891246
27,run_20260326_153808_b8b215f2,catboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.263086,0.734444,26.775995,18.323889,0.923622
26,run_20260326_153803_42cfc32e,xgboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.294839,0.789609,24.822468,15.990897,0.911718
11,run_20260326_145008_f450e889,hist_gbr,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.385959,0.978383,27.780549,17.784059,0.800832
18,run_20260326_153424_ca1c3f56,hist_gbr,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.390197,0.991819,31.695050,20.857448,0.861092
12,run_20260326_145015_7449d4db,xgboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.406413,1.010100,32.809779,20.745050,0.787709
13,run_20260326_145020_8a72433a,catboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel1,nan_friendly,0.415025,1.018969,34.247226,21.722711,0.783965
19,run_20260326_153428_2881c7e4,xgboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.433095,1.023100,37.220535,22.308114,0.852191
20,run_20260326_153434_9578ee89,catboost,Data_with_NaNs,BA_TotActPwr_BESS_AC_Panel2,nan_friendly,0.447766,1.064100,58.035112,32.728298,0.840107
32,run_20260326_154417_fa47de0d,hist_gbr,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.166354,1.975490,13.033215,12.781590,0.939672
33,run_20260326_154422_329111d4,xgboost,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.160391,1.982293,12.832649,12.577479,0.939256
34,run_20260326_154429_e3f2adce,catboost,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.223257,2.090055,13.653967,13.403584,0.932472
39,run_20260326_154654_55002824,hist_gbr,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.326824,2.281546,12.882714,12.626891,0.919027
41,run_20260326_154704_3af136cf,catboost,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.338579,2.363711,12.909499,12.686420,0.913090
40,run_20260326_154659_796f7f5f,xgboost,Data_with_NaNs,BU_TotActPwr_Academy,nan_friendly,1.387868,2.461573,12.819114,12.641447,0.905745
45,run_20260326_154922_31a527a4,xgboost,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.090972,0.172347,6.118888,5.658857,0.985611
44,run_20260326_154859_42489288,random_forest,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.091427,0.180622,5.675108,5.322888,0.984196
52,run_20260326_155207_f9a2d458,xgboost,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.094804,0.192072,6.081118,5.539115,0.982288
51,run_20260326_155037_96cfe428,random_forest,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.094316,0.198051,6.105730,5.558563,0.981169
49,run_20260326_155035_da2c1372,linear_regression,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.118009,0.231712,7.718715,7.027587,0.974223
50,run_20260326_155036_abef64dc,ridge,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.118010,0.231714,7.718866,7.027577,0.974223
43,run_20260326_154858_98ecd460,ridge,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.140397,0.242415,9.139957,8.514547,0.971533
42,run_20260326_154857_f3d804f1,linear_regression,Imputed_data,BU_TotActPwr_Tech_Room,dense,0.140518,0.242420,9.148846,8.523091,0.971532
1,run_20260326_135955_2ded4f36,ridge,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.227476,0.593980,24.802236,15.840235,0.927328
0,run_20260326_135954_1beb8be6,linear_regression,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.227493,0.593984,24.804799,15.843181,0.927327
21,run_20260326_153558_0eb3095a,linear_regression,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.257913,0.643850,32.183966,24.271127,0.941469
22,run_20260326_153559_1c0871c7,ridge,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.257899,0.643852,32.183690,24.267914,0.941468
2,run_20260326_135956_f45e2aad,random_forest,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.274168,0.675291,29.245611,16.788629,0.906070
3,run_20260326_140213_03187aa3,xgboost,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.243553,0.727950,20.211308,11.535189,0.890849
24,run_20260326_153752_7d2b0fe8,xgboost,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.297907,0.788603,27.561726,16.942815,0.912191
7,run_20260326_144930_d1d87d89,linear_regression,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.404072,0.908163,33.315099,24.946101,0.826890
8,run_20260326_144931_d5b9718a,ridge,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.404053,0.908227,33.306838,24.939525,0.826866
9,run_20260326_144931_e11f3e83,random_forest,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.434171,0.947023,40.387864,24.652634,0.811759
17,run_20260326_153419_890c2673,xgboost,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.423238,0.964041,39.413682,22.869742,0.867654
10,run_20260326_145001_1266ed1a,xgboost,Imputed_data,BA_TotActPwr_BESS_AC_Panel1,dense,0.406662,1.010730,33.136872,21.011118,0.785581
16,run_20260326_153347_00337d97,random_forest,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.476204,1.022418,43.971712,26.048720,0.851141
23,run_20260326_153600_049dc232,random_forest,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.398067,1.078215,33.177037,20.959548,0.835854
15,run_20260326_153347_035e8418,ridge,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.497750,1.122526,58.430143,36.507134,0.820563
14,run_20260326_153346_2dd42ec2,linear_regression,Imputed_data,BA_TotActPwr_BESS_AC_Panel2,dense,0.497769,1.122532,58.429234,36.510321,0.820561
28,run_20260326_154237_239e49c3,linear_regression,Imputed_data,BU_TotActPwr_Academy,dense,1.010545,1.557895,12.901709,12.404494,0.963066
29,run_20260326_154237_a74253da,ridge,Imputed_data,BU_TotActPwr_Academy,dense,1.010540,1.557897,12.901594,12.404396,0.963066
36,run_20260326_154624_410a4c6a,ridge,Imputed_data,BU_TotActPwr_Academy,dense,1.171920,1.795383,14.463125,13.483778,0.949576
35,run_20260326_154624_eadf4471,linear_regression,Imputed_data,BU_TotActPwr_Academy,dense,1.171929,1.795389,14.463099,13.483814,0.949576
30,run_20260326_154238_9963abd2,random_forest,Imputed_data,BU_TotActPwr_Academy,dense,1.157964,1.889716,13.451217,12.863047,0.945657
31,run_20260326_154411_3aed7e18,xgboost,Imputed_data,BU_TotActPwr_Academy,dense,1.148421,1.944004,12.758441,12.474120,0.942490
37,run_20260326_154625_f7aa5d98,random_forest,Imputed_data,BU_TotActPwr_Academy,dense,1.367828,2.366264,13.004725,12.700836,0.912411
38,run_20260326_154649_d1218964,xgboost,Imputed_data,BU_TotActPwr_Academy,dense,1.403895,2.503871,12.910317,12.717561,0.901927

# Best Model Summary

| Target | Best Model Summary |
|---|---|
| **BU_TotActPwr_Tech_Room** | **NaNs:** XGBoost (RMSE **0.1628**)  •  **Imputed:** XGBoost (RMSE **0.1723**)  → **NaNs slightly better** |
| **BU_TotActPwr_SDB_EL_Substation** | **NaNs:** CatBoost (RMSE **0.4880**)  •  **Imputed:** Not available |
| **BA_TotActPwr_BESS_AC_Panel1** | **NaNs:** HistGBR (RMSE **0.6951**)  •  **Imputed:** Linear/Ridge (RMSE **0.5940**)  → **Imputed better** |
| **BA_TotActPwr_BESS_AC_Panel2** | **NaNs:** HistGBR (RMSE **0.7042**)  •  **Imputed:** Linear/Ridge (RMSE **0.6439**)  → **Imputed better** |
| **BU_TotActPwr_Academy** | **NaNs:** HistGBR (RMSE **1.9755**)  •  **Imputed:** Linear/Ridge (RMSE **1.5579**)  → **Imputed better** |

## Overall
In most targets, **Imputed Data performed better**.  
The main exception is **Tech Room**, where **Data with NaNs performed slightly better**.